-- V8: Align dlp_logs schema with DlpLog entity when table already exists from V7.
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS username VARCHAR(150) NULL;
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS endpoint VARCHAR(255) NULL;
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS http_method VARCHAR(10) NULL;
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS risk_level VARCHAR(20) NULL DEFAULT 'LOW';
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS blocked BOOLEAN NULL DEFAULT FALSE;
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS client_ip VARCHAR(45) NULL;
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS user_agent VARCHAR(500) NULL;
ALTER TABLE dlp_logs ADD COLUMN IF NOT EXISTS created_at DATETIME(6) NULL;
